/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FormAutenticacao.java
 *
 * Created on 25/Fev/2011, 16:42:20
 */
package numidia.model.ui;

import pt.gov.cartaodecidadao.PTEID_Pins;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.LinkedHashSet;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author bnazare
 */
public class StandaloneAuthForm extends javax.swing.JFrame {

    private static final String PKCS11LIB = "opensc-pkcs11";

    /** Creates new form FormAutenticacao */
    public StandaloneAuthForm() {
        initComponents();
    }

    public void createURL() {
        painelAutenticacaoSimples1.setHeadless(false);
        painelAutenticacaoSimples1.init();
        Set<CCAttribute> attrSet = new LinkedHashSet();
        attrSet.add(new CCAttribute("name", false));
        attrSet.add(new CCAttribute("nic", true));
        attrSet.add(new CCAttribute("TaxNo", true));
        attrSet.add(new CCAttribute("SocialSecurityNo", true));
        attrSet.add(new CCAttribute("HealthNo", true));
        attrSet.add(new CCAttribute("streetName", true));
        attrSet.add(new CCAttribute("userNotes", true));
        attrSet.add(new CCAttribute("photo", true));
        //painelAutenticacaoSimples1.setAttrSet(attrSet);
        URL rootURL;
        try {
            painelAutenticacaoSimples1.setSubmitUrl(new URL("https://li148-217.members.linode.com/webapp/submit.jsp"));
        } catch (MalformedURLException ex) {
            Logger.getLogger(StandaloneAuthForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }



    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelAutenticacaoSimples1 = new StandaloneAuthPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painelAutenticacaoSimples1.setPreferredSize(new java.awt.Dimension(180, 180));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelAutenticacaoSimples1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelAutenticacaoSimples1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            StandaloneAuthForm form = new StandaloneAuthForm();
            form.setVisible(true);

            form.createURL();
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private StandaloneAuthPanel painelAutenticacaoSimples1;
    // End of variables declaration//GEN-END:variables
}
